import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Refaat Bitar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container font-body mx-auto min-h-full'>
        <h1 className="font-title text-4xl py-6">Welcome to my website!</h1>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore, quia
          nostrum voluptas libero voluptatem saepe voluptates dignissimos odio
          labore maiores est, itaque deleniti, soluta optio corrupti cupiditate
          consequuntur qui ullam?
        </p>
      </main>
    </>
  );
};

export default Home;
